# Generated by Django 4.1.3 on 2022-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_gamer', '0004_alter_game_is_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
