# Generated by Django 4.1.3 on 2022-12-13 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_gamer', '0005_game_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='borrower',
        ),
        migrations.AddField(
            model_name='gamer',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
